# Generated by Django 5.0.3 on 2024-03-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='description',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
